django/faces/urls.py
from django.conf.urls import url
from django.contrib import admin
from faces import views

urlpatterns = [
	url(r'^appcall', views.appcall, name='appcall'),
    url(r'^submit', views.homepage.as_view(), name='submit'),
	url(r'^score', views.homepage.as_view(), name='home'),
    url(r'^$', views.master.as_view(), name='master'),
]

django/political_faces_proj/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from faces import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('faces.urls', namespace="main", app_name="faces")),

]

django/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
	url(r'^', include('faces.urls', namespace='faces')),
    url(r'^admin/', admin.site.urls),
]

django/faces/forms.py
from django import forms
 
# from faces.models import Face
 
 
class UploadFileForm(forms.Form):
     
    file = forms.FileField(required=True)

django/faces/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response
from django.views.generic import View
from django.shortcuts import render, redirect
from faces.forms import UploadFileForm
from faces.master import ApiCall
import base64
# import PIL
import io
import os
# import pprint
from django.conf import settings

# import pudb

class master(View):
    template='master.html'
    def get(self,request):
        return render(request, self.template, {})

class homepage(View):
    api = ApiCall()


    template='homepage.html'
    def get(self,request):
        context={'forms':UploadFileForm(),
                 'polcomp':"https://www.politicalcompass.org/analysis2",
        }
        return render(request,self.template, context)
    def post(self,request):

        # pu.db
        form = UploadFileForm(request.POST, request.FILES)
        # print (request.FILES['file'].values())
        # print (vars(request.FILES).keys())
        # print(request.FILES)
        if form.is_valid():

            img = request.FILES['file']
            self.api.picture=img.file
            self.api.run()
            api = self.api.graph()
            context={
                'econ':api[0],
                'social':api[1],
                'forms':UploadFileForm(),
                'polcomp':"https://www.politicalcompass.org/analysis2?ec=" + str(api[0]) + "&soc=" + str(api[1])
            }

        else:
            return self.get(request)
        return render(request, self.template, context)

def appcall(request):
    api = ApiCall()
    imgData = ""

    f = request.body
    f= str(f)
    f=f[8:-2]
    # print(f[:10])
    # for line in f:
        # print(line)
    f = f.replace('%0A', '\n')
    f = f.replace('-', '+')
    f = f.replace('_', '/')
    f = f.replace('%3D', '=')
        # imgData += line
    # print(f)
    # imgData += f
    # print(imgData)

    fh = open("imageToSave.png", "wb")
    fh.write(base64.b64decode(f))
    fh.close()
    fh = open('imageToSave.png', 'rb')
    api.picture=fh
    resp = api.run()
    os.remove("imageToSave.png")
    # print (api)
    # api = api.graph()
    # print(api[0])
    # print(api[1])
    context={
        'econ':resp[0],
        'social':resp[1],
    }
    return JsonResponse(context)
        
# appcall()





# class score(View):
#     api = ApiCall()
#     template='homepage.html'
   
#     def post(self,request):
#         api.graph()

django/faces/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="icon" href="static/images/logo.png">
	<meta charset="UTF-8">
  <title>PolitiPic</title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="static/js/wow.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js"></script>
  <script src="static/js/jquery.ajaxchimp.min.js"></script>
  <script src="static/js/custom.min.js"></script>

	<script src="static/js/django_ajax.js"></script>
	<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  
	<!-- Latest compiled and minified CSS -->
  
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- <link rel="apple-touch-icon" href="apple-touch-icon.png"> -->
  <!-- Include Bootstrap Css -->
  <link rel="stylesheet" href="static/css/bootstrap.css">
  <!-- Include Bootstrap Min Css -->
  <link rel="stylesheet" href="static/css/bootstrap-theme.min.css">
  <!-- Include Animate Min Css -->
  <link rel="stylesheet" href="static/css/animate.min.css">
  <!-- Include Fontawesome Min Css -->
  <link rel="stylesheet" href="static/css/font-awesome.min.css">
  <!-- Include Magnific PopUp Css -->
  <link rel="stylesheet" href="static/css/magnific-popup.css">
  <!-- bxSlider CSS file -->
  <link href="static/css/jquery.bxslider.css" rel="stylesheet" />
  <!-- Include Style Css -->
  <link rel="stylesheet" href="static/css/style.css">
  <!-- Include Responsive Css -->
  <link rel="stylesheet" href="static/css/responsive.min.css">
  <!-- Include Modernizer Js -->
  <script src="static/js/modernizr-2.8.3-respond-1.4.2.min.js"></script>

</head>

  <header id="masthead" class="masthead navbar navbar-default navbar-fixed-top">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu">
          <i class="fa fa-bars"></i>
        </button>
        
        <a class="navbar-brand" href="./"><img src="static/images/logo.png" alt="Site Logo" style="height:30px"></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <nav id="main-menu" class="navbar-collapse pull-right collapse">
        <ul class="nav navbar-nav">

<!--           <li class="active"><a href="#main-slider">Home</a></li>
 -->          <li class="active"><a href="{% url 'faces:home' %}">Find your score</a></li>


        </ul>
      </nav><!-- /.navbar-collapse -->
    </div><!-- /.container -->
  </header><!-- /#masthead -->
<body>


		{% block content %}

		{% endblock content %}
	
</body>
</html>

django/faces/templates/homepage.html
{% extends "base.html" %}

{% block content %}
<div class= "container">
<div class ="submitpic" style="padding-bottom:10px;">

    <form name='pictures' action = '{% url "main:submit" %}' method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{forms}}
     <input id ="submit" type="submit" value="submit" style="width:100px;">
<div class="instructions">
     <div>Step 1: Pick an image of a face to test</div>
     <div>Step 2: Submit the image</div>
    <div>Step 3: Our custom algorithm, with the assistance <br>
      of Google's Vision API, will analyze the face, <br>
      identify 34 distinct landmarks and return a<br> 
      prediction of the person's economic and social views.</div>
      <br><br>
      <div>For more information about your score, go to <a href='{{ polcomp }}'> The Political Compass</a>.</div>
    <div></div>

    </div>
    </form>
</div>

<script>
google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {
        var data =  google.visualization.arrayToDataTable
            ([['X', 'Y', {'type': 'string', 'role': 'style'},{'type': 'string', 'role': 'tooltip'}],
              [1, 9.8, null,'Adolf Hitler'],
              [8, 9, null,' Donald Trump'],
              [8, 8.5, null,'Jeb Bush'],
              [8.5, 8.5, null,' Ted Cruz'],
                          {% if econ %}
              [{{econ|floatformat:2}}, {{social|floatformat:2}},'point { size: 10; shape-type: star; fill-color: #a52714; }','Your score'],
            {% endif %}
              [9, 7.5, null,' Marco Rubio'],
              [7, 4, null, 'Hillary Clinton'],
              [-2, 0, null, 'Bernie Sanders'],
              [-6, -4, null, 'Mahatma Gandhi'],
              [7, -2, null, 'Milton Friedman'],


        ]);

        var options = {
          legend: 'none',
          hAxis: { title:'Libertarian',minValue: -10, maxValue: 10 },
          vAxis: { title:'Left',minValue: -10, maxValue: 10 },
          title: "Authoritarian",
          curveType: 'function',
          pointSize: 7,
          dataOpacity: 0.3,
          fontSize: 20
        };

        var chart = new google.visualization.ScatterChart(document.getElementById('chart_div'));
        chart.draw(data, options);
              movingAuthoritarian();


    }
    var movingAuthoritarian = function(){
    $('text:contains("Authoritarian")').attr("text-anchor", "middle")
    $('text:contains("Authoritarian")').attr("x", "400")
    $('text:contains("Authoritarian")').attr("font-weight", "")
    $('text:contains("Authoritarian")').attr("font-style", "italic")

    }
    </script>

<div id = "chart_div" style="width:800px; height:500px; margin: 0px;"></div>

</div>
<link rel="stylesheet" href="static/css/responsive.css">

{% endblock %}